name: test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install protostar
        run: curl -L https://raw.githubusercontent.com/software-mansion/protostar/master/install.sh | bash
      - name: Create lib directory
        # as there are no libs in this repository, the directory isn't created during the installation step
        run: mkdir lib
      - name: Activate protostar
        run: echo "/home/runner/.protostar/dist/protostar" >> $GITHUB_PATH
      - name: Run tests
        run: protostar test
